export DOTBASHRC_LOADED=1
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"
export LC_ALL="en_US.UTF-8"

# Go
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

# StepLib environments
[[ -s "$HOME/.profiles/steplib_profile" ]] && source "$HOME/.profiles/steplib_profile"

# Bitrise environments
[[ -s "$HOME/.profiles/bitrise_profile" ]] && source "$HOME/.profiles/bitrise_profile"

# keep a newline at the end of this file

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
